services:
  lint:
    build:
      context: .
      dockerfile: DockerfileForDockerCompose
    image: ${TEXT_LINT_IMAGE_NAME}:${TEXT_LINT_IMAGE_TAG}
    volumes:
      - .:/workspace
      - /workspace/node_modules
    working_dir: /workspace
    command: yarn lint
