# 「n版」または「n版m刷」の特定タグが push されると、
# 電子版および印刷用 PDF を添付したリリースが作成します。

name: Publish and Release PDF

on:
  push:
    tags:
      - '*版'
      - '*版*刷'

permissions:
  contents: write

jobs:
  publish-and-release-pdf:
    name: Build and Publish PDF
    runs-on: ubuntu-latest

    # 環境変数を定義
    env:
      # 生成される PDF のパス
      EBOOK_PDF_PATH: ./output/output.pdf
      PRESS_PDF_PATH: ./output/press.pdf
    
    steps:

      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node.jsをセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      
      # PDFを作成する
      - name: make PDF
        run: |
          corepack enable
          yarn install --immutable
          
          yarn pdf
          if [ ! -f "${EBOOK_PDF_PATH}" ]; then
            echo "エラー: 電子版 PDF の生成に失敗しました。"
            exit 1
          fi

          make press
          if [ ! -f "${PRESS_PDF_PATH}" ]; then
            echo "エラー: 電子版 PDF の生成に失敗しました。"
            exit 1
          fi
          
      # リリースの作成
      - name: Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          generate_release_notes: true
          files: |
            ${{ env.EBOOK_PDF_PATH }}
            ${{ env.PRESS_PDF_PATH }}
